version: '3.7'

services:
  vgt-web-app:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 120s
    image: qaziok/vgt-web-app:main
    environment:
      - VUE_APP_API_URL=/api
      - VUE_APP_API_TIMEOUT=10000
      - VUE_APP_API_PURCHASE_TIMEOUT=60000
    depends_on:
      - vgt-api
    networks:
      - backend

  vgt-api:
    image: qaziok/vgt-api:main
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 120s
    depends_on:
      - vgt-saga-hotel
      - vgt-saga-flight
      - vgt-saga-orders
      - vgt-saga-payment
    networks:
      - backend

  vgt-saga-hotel:
    image: qaziok/vgt-saga-hotel:main
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 120s
    env_file:
      - .env.db.config
      - .env.rabbit.config
      - .env.config
    depends_on:
      - vgt-broker
    networks:
      - backend
      - database

  vgt-saga-flight:
    image: qaziok/vgt-saga-flight:main
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 120s
    env_file:
      - .env.db.config
      - .env.rabbit.config
      - .env.config
    depends_on:
      - vgt-broker
    networks:
      - backend
      - database

  vgt-saga-orders:
    image: qaziok/vgt-saga-orders:main
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 120s
    env_file:
      - .env.db.config
      - .env.rabbit.config
      - .env.config
    depends_on:
      - vgt-broker
      - vgt-saga-hotel
      - vgt-saga-flight
    networks:
      - backend
      - database

  vgt-saga-payment:
    image: qaziok/vgt-saga-payment:main
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 120s
    env_file:
      - .env.rabbit.config
      - .env.config
    depends_on:
      - vgt-broker
    networks:
      - backend

  vgt-broker:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 120s
    ports:
      - "18434:15672"
      - "18435:5672"
    image: qaziok/vgt-broker:main
    networks:
      - backend

networks:
  backend:
    driver: overlay
    name: RSWW_184347_vgt-network
  database:
    external: true
    name: admin-postgres_default
