version: '3.7'

services:
  vgt-web-app:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    image: qaziok/vgt-web-app:latest
    ports:
      - "18434:80"
    env:
      VUE_APP_API_URL=/api
      VUE_APP_API_TIMEOUT=10000
      VUE_APP_API_PURCHASE_TIMEOUT=60000
    depends_on:
      - vgt-api

  vgt-api:
    image: qaziok/vgt-api:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s
  depends_on:
    - vgt-saga-hotel
    - vgt-saga-flight
    - vgt-saga-orders
    - vgt-saga-payment

  vgt-saga-hotel:
    image: qaziok/vgt-saga-hotel:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s
    env-file:
      - .env.db.config
      - .env.rabbit.config
    env:
      RABBIT_REPLIES: saga-replies-queue
      RABBIT_HOTEL: saga-hotel-queue
      DB_NAME_HOTEL: hotels
    depends_on:
      - vgt-broker

  vgt-saga-flight:
    image: qaziok/vgt-saga-flight:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s
    env-file:
      - .env.db.config
      - .env.rabbit.config
    env:
      RABBIT_REPLIES: saga-replies-queue
      RABBIT_FLIGHT: saga-flight-queue
      DB_NAME_FLIGHT: flights
    depends_on:
      - vgt-broker

  vgt-saga-orders:
    image: qaziok/vgt-saga-orders:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s
    env-file:
      - .env.db.config
      - .env.rabbit.config
    env:
      BACKEND_REQUESTS: backend-to-saga-queue
      BACKEND_REPLIES: saga-to-backends
      RABBIT_REPLIES: saga-replies-queue
      RABBIT_ORDER: saga-order-queue
      RABBIT_PAYMENT: saga-payment-queue
      RABBIT_HOTEL: saga-hotel-queue
      RABBIT_FLIGHT: saga-flight-queue
      DB_NAME_SAGA: saga
    depends_on:
      - vgt-broker
      - vgt-saga-hotel
      - vgt-saga-flight

  vgt-saga-payment:
    image: qaziok/vgt-saga-payment:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s
    env-file:
      - .env.db.config
      - .env.rabbit.config
    env:
      RABBIT_REPLIES: saga-replies-queue
      RABBIT_PAYMENT: saga-payment-queue
      PAYMENT_MIN_DELAY: 0
      PAYMENT_MAX_DELAY: 100
    depends_on:
      - vgt-broker

  vgt-broker:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s
    image: qaziok/vgt-broker:latest


